services:
  app:
    build: .
    ports:
      - "5030:5030"
    env_file:
      - .env
    environment:
      - TZ=${TZ:-Europe/Madrid}
      - PLEX_BASEURL=${PLEX_BASEURL}
      - TRAKT_CLIENT_ID=${TRAKT_CLIENT_ID}
      - TRAKT_CLIENT_SECRET=${TRAKT_CLIENT_SECRET}
      - SIMKL_CLIENT_ID=${SIMKL_CLIENT_ID}
      - SIMKL_CLIENT_SECRET=${SIMKL_CLIENT_SECRET}
