version: '3'
services:
  app:
    image: drakonis96/plexytrack
    ports:
      - "5030:5030"
    env_file:
      - .env
    environment:
      - TZ=${TZ:-Europe/Madrid}

      - TRAKT_CLIENT_ID=${TRAKT_CLIENT_ID}
      - TRAKT_CLIENT_SECRET=${TRAKT_CLIENT_SECRET}
      - SIMKL_CLIENT_ID=${SIMKL_CLIENT_ID}
      - SIMKL_CLIENT_SECRET=${SIMKL_CLIENT_SECRET}
      
      # Optional custom redirect URIs
      #- TRAKT_REDIRECT_URI=${TRAKT_REDIRECT_URI:-}
      #- SIMKL_REDIRECT_URI=${SIMKL_REDIRECT_URI:-}

