version: '3'
services:
  app:
    image: drakonis96/plexytrack
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - TZ=${TZ:-Europe/Madrid}
      - PLEX_BASEURL=${PLEX_BASEURL}
      - PLEX_TOKEN=${PLEX_TOKEN}
      - TRAKT_CLIENT_ID=${TRAKT_CLIENT_ID}
      - TRAKT_CLIENT_SECRET=${TRAKT_CLIENT_SECRET}
      - SIMKL_CLIENT_ID=${SIMKL_CLIENT_ID}
      - SIMKL_CLIENT_SECRET=${SIMKL_CLIENT_SECRET}
      - TRAKT_REDIRECT_URI=${TRAKT_REDIRECT_URI:-urn:ietf:wg:oauth:2.0:oob}
      - SIMKL_REDIRECT_URI=${SIMKL_REDIRECT_URI:-urn:ietf:wg:oauth:2.0:oob}

